@TaboAni.Api_HostAddress = http://localhost:5091

GET {{TaboAni.Api_HostAddress}}/api/v1/marketplace/categories
Accept: application/json

###

GET {{TaboAni.Api_HostAddress}}/api/v1/marketplace/listings?page=1&pageSize=20
Accept: application/json

###

GET {{TaboAni.Api_HostAddress}}/api/v1/admin/marketplace/listings?page=1&pageSize=20
Accept: application/json

###
